imports:
  - { resource: ../../../../src/Unpaid/Shared/Infrastructure/Symfony/DependencyInjection/unpaid_database.yaml }
  - { resource: ../../../../src/Unpaid/Shared/Infrastructure/Symfony/DependencyInjection/unpaid_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Financial\Apps\Backoffice\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Financial\Apps\Backoffice\Backend\Command\:
    resource: '../src/Command'
    tags: [ 'console.command' ]

  Financial\:
    resource: '../../../../src'

  Financial\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
