framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Financial\Tests\:
    resource: '../../../../tests'

  Financial\Shared\Domain\RandomNumberGenerator: '@Financial\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'
