services:
  _defaults:
    autoconfigure: true
    autowire: true


  Financial\Apps\Backoffice\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Financial\:
    resource: '../../../../src'
