imports:
  - { resource: ../../../../src/Unpaid/Shared/Infrastructure/Symfony/DependencyInjection/unpaid_database.yaml }
  - { resource: ../../../../src/Unpaid/Shared/Infrastructure/Symfony/DependencyInjection/unpaid_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:
    Financial\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'codely.domain_event_subscriber' ]

  Financial\Apps\Backoffice\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Financial\Apps\Backoffice\Backend\Command\:
    resource: '../src/Command'
    tags: [ 'console.command' ]

  Financial\:
    resource: '../../../../src'

  # -- TAGGING --
  Financial\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged codely.domain_event_subscriber ]
    lazy: true

  Financial\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
